onlyBuiltDependencies:
  - '@sentry/cli'
  - '@shopify/react-native-skia'
patchedDependencies:
  react-native-webview: patches/react-native-webview.patch
  react-native-track-player: patches/react-native-track-player.patch
