onlyBuiltDependencies:
  - '@sentry/cli'
  - '@shopify/react-native-skia'
  - esbuild
patchedDependencies:
  react-native-track-player: patches/react-native-track-player.patch
  '@iternio/react-native-auto-play': patches/@iternio__react-native-auto-play.patch
  drizzle-orm@1.0.0-beta.16-ea816b6: patches/drizzle-orm@1.0.0-beta.16-ea816b6.patch
