onlyBuiltDependencies:
  - '@sentry/cli'
patchedDependencies:
  react-native-webview: patches/react-native-webview.patch
  '@weights-ai/react-native-track-player': patches/@weights-ai__react-native-track-player.patch
