onlyBuiltDependencies:
  - '@sentry/cli'
  - '@shopify/react-native-skia'
  - esbuild
patchedDependencies:
  react-native-webview: patches/react-native-webview.patch
  react-native-track-player: patches/react-native-track-player.patch
  '@iternio/react-native-auto-play': patches/@iternio__react-native-auto-play.patch
