# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 14 Plus",
  "iPhone 14 Pro Max",
  "iPhone 8 Plus",
])

languages([
  "en-US",
  "es-ES",
  "fr-FR",
  "ja",
  "nl-NL",
  "zh-Hans",
])

# The name of the scheme which contains the UI Tests
scheme("Fintunes")
workspace("ios/Fintunes.xcworkspace")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot

# Enabling this option will prevent displaying the simulator window
headless(false)

# Enabling this option will configure the Simulator to be in dark mode (false for light, true for dark)
dark_mode(false)